# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /home/zenm/CustomApplications/UnrealEngine-5.0.0-early-access-1
GAMEPROJECTFILE =/mnt/Game_Drive/Unreal/UnrealProjects/Building_Escape_3/Building_Escape_3.uproject

TARGETS = \
	BenchmarkTool-Linux-Debug  \
	BenchmarkTool-Linux-DebugGame  \
	BenchmarkTool-Linux-Shipping  \
	BenchmarkTool-Linux-Test  \
	BenchmarkTool \
	BlankProgram-Linux-Debug  \
	BlankProgram-Linux-DebugGame  \
	BlankProgram-Linux-Shipping  \
	BlankProgram-Linux-Test  \
	BlankProgram \
	BuildPatchTool-Linux-Debug  \
	BuildPatchTool-Linux-DebugGame  \
	BuildPatchTool-Linux-Shipping  \
	BuildPatchTool-Linux-Test  \
	BuildPatchTool \
	ChaosVisualDebugger-Linux-Debug  \
	ChaosVisualDebugger-Linux-DebugGame  \
	ChaosVisualDebugger-Linux-Shipping  \
	ChaosVisualDebugger-Linux-Test  \
	ChaosVisualDebugger \
	CrashReportClient-Linux-Debug  \
	CrashReportClient-Linux-DebugGame  \
	CrashReportClient-Linux-Shipping  \
	CrashReportClient-Linux-Test  \
	CrashReportClient \
	CrashReportClientEditor-Linux-Debug  \
	CrashReportClientEditor-Linux-DebugGame  \
	CrashReportClientEditor-Linux-Shipping  \
	CrashReportClientEditor-Linux-Test  \
	CrashReportClientEditor \
	DatasmithCADWorker-Linux-Debug  \
	DatasmithCADWorker-Linux-DebugGame  \
	DatasmithCADWorker-Linux-Shipping  \
	DatasmithCADWorker-Linux-Test  \
	DatasmithCADWorker \
	DatasmithFacadeCSharp-Linux-Debug  \
	DatasmithFacadeCSharp-Linux-DebugGame  \
	DatasmithFacadeCSharp-Linux-Shipping  \
	DatasmithFacadeCSharp-Linux-Test  \
	DatasmithFacadeCSharp \
	DatasmithMax2016-Linux-Debug  \
	DatasmithMax2016-Linux-DebugGame  \
	DatasmithMax2016-Linux-Shipping  \
	DatasmithMax2016-Linux-Test  \
	DatasmithMax2016 \
	DatasmithMax2017-Linux-Debug  \
	DatasmithMax2017-Linux-DebugGame  \
	DatasmithMax2017-Linux-Shipping  \
	DatasmithMax2017-Linux-Test  \
	DatasmithMax2017 \
	DatasmithMax2018-Linux-Debug  \
	DatasmithMax2018-Linux-DebugGame  \
	DatasmithMax2018-Linux-Shipping  \
	DatasmithMax2018-Linux-Test  \
	DatasmithMax2018 \
	DatasmithMax2019-Linux-Debug  \
	DatasmithMax2019-Linux-DebugGame  \
	DatasmithMax2019-Linux-Shipping  \
	DatasmithMax2019-Linux-Test  \
	DatasmithMax2019 \
	DatasmithMax2020-Linux-Debug  \
	DatasmithMax2020-Linux-DebugGame  \
	DatasmithMax2020-Linux-Shipping  \
	DatasmithMax2020-Linux-Test  \
	DatasmithMax2020 \
	DatasmithMax2021-Linux-Debug  \
	DatasmithMax2021-Linux-DebugGame  \
	DatasmithMax2021-Linux-Shipping  \
	DatasmithMax2021-Linux-Test  \
	DatasmithMax2021 \
	DatasmithNavisworks2019-Linux-Debug  \
	DatasmithNavisworks2019-Linux-DebugGame  \
	DatasmithNavisworks2019-Linux-Shipping  \
	DatasmithNavisworks2019-Linux-Test  \
	DatasmithNavisworks2019 \
	DatasmithNavisworks2020-Linux-Debug  \
	DatasmithNavisworks2020-Linux-DebugGame  \
	DatasmithNavisworks2020-Linux-Shipping  \
	DatasmithNavisworks2020-Linux-Test  \
	DatasmithNavisworks2020 \
	DatasmithRevit2018-Linux-Debug  \
	DatasmithRevit2018-Linux-DebugGame  \
	DatasmithRevit2018-Linux-Shipping  \
	DatasmithRevit2018-Linux-Test  \
	DatasmithRevit2018 \
	DatasmithRevit2019-Linux-Debug  \
	DatasmithRevit2019-Linux-DebugGame  \
	DatasmithRevit2019-Linux-Shipping  \
	DatasmithRevit2019-Linux-Test  \
	DatasmithRevit2019 \
	DatasmithRevit2020-Linux-Debug  \
	DatasmithRevit2020-Linux-DebugGame  \
	DatasmithRevit2020-Linux-Shipping  \
	DatasmithRevit2020-Linux-Test  \
	DatasmithRevit2020 \
	DatasmithRevit2021-Linux-Debug  \
	DatasmithRevit2021-Linux-DebugGame  \
	DatasmithRevit2021-Linux-Shipping  \
	DatasmithRevit2021-Linux-Test  \
	DatasmithRevit2021 \
	DatasmithRhino6-Linux-Debug  \
	DatasmithRhino6-Linux-DebugGame  \
	DatasmithRhino6-Linux-Shipping  \
	DatasmithRhino6-Linux-Test  \
	DatasmithRhino6 \
	DatasmithRhino7-Linux-Debug  \
	DatasmithRhino7-Linux-DebugGame  \
	DatasmithRhino7-Linux-Shipping  \
	DatasmithRhino7-Linux-Test  \
	DatasmithRhino7 \
	DatasmithSDK-Linux-Debug  \
	DatasmithSDK-Linux-DebugGame  \
	DatasmithSDK-Linux-Shipping  \
	DatasmithSDK-Linux-Test  \
	DatasmithSDK \
	DatasmithSketchUp2017-Linux-Debug  \
	DatasmithSketchUp2017-Linux-DebugGame  \
	DatasmithSketchUp2017-Linux-Shipping  \
	DatasmithSketchUp2017-Linux-Test  \
	DatasmithSketchUp2017 \
	DatasmithSketchUp2018-Linux-Debug  \
	DatasmithSketchUp2018-Linux-DebugGame  \
	DatasmithSketchUp2018-Linux-Shipping  \
	DatasmithSketchUp2018-Linux-Test  \
	DatasmithSketchUp2018 \
	DatasmithSketchUp2019-Linux-Debug  \
	DatasmithSketchUp2019-Linux-DebugGame  \
	DatasmithSketchUp2019-Linux-Shipping  \
	DatasmithSketchUp2019-Linux-Test  \
	DatasmithSketchUp2019 \
	DatasmithSketchUp2020-Linux-Debug  \
	DatasmithSketchUp2020-Linux-DebugGame  \
	DatasmithSketchUp2020-Linux-Shipping  \
	DatasmithSketchUp2020-Linux-Test  \
	DatasmithSketchUp2020 \
	EpicWebHelper-Linux-Debug  \
	EpicWebHelper-Linux-DebugGame  \
	EpicWebHelper-Linux-Shipping  \
	EpicWebHelper-Linux-Test  \
	EpicWebHelper \
	HeadlessChaos-Linux-Debug  \
	HeadlessChaos-Linux-DebugGame  \
	HeadlessChaos-Linux-Shipping  \
	HeadlessChaos-Linux-Test  \
	HeadlessChaos \
	InterchangeWorker-Linux-Debug  \
	InterchangeWorker-Linux-DebugGame  \
	InterchangeWorker-Linux-Shipping  \
	InterchangeWorker-Linux-Test  \
	InterchangeWorker \
	LiveCodingConsole-Linux-Debug  \
	LiveCodingConsole-Linux-DebugGame  \
	LiveCodingConsole-Linux-Shipping  \
	LiveCodingConsole-Linux-Test  \
	LiveCodingConsole \
	ShaderCompileWorker-Linux-Debug  \
	ShaderCompileWorker-Linux-DebugGame  \
	ShaderCompileWorker-Linux-Shipping  \
	ShaderCompileWorker-Linux-Test  \
	ShaderCompileWorker \
	SlateViewer-Linux-Debug  \
	SlateViewer-Linux-DebugGame  \
	SlateViewer-Linux-Shipping  \
	SlateViewer-Linux-Test  \
	SlateViewer \
	SwitchboardListener-Linux-Debug  \
	SwitchboardListener-Linux-DebugGame  \
	SwitchboardListener-Linux-Shipping  \
	SwitchboardListener-Linux-Test  \
	SwitchboardListener \
	TestPAL-Linux-Debug  \
	TestPAL-Linux-DebugGame  \
	TestPAL-Linux-Shipping  \
	TestPAL-Linux-Test  \
	TestPAL \
	TextureShareSDK-Linux-Debug  \
	TextureShareSDK-Linux-DebugGame  \
	TextureShareSDK-Linux-Shipping  \
	TextureShareSDK-Linux-Test  \
	TextureShareSDK \
	UnrealFileServer-Linux-Debug  \
	UnrealFileServer-Linux-DebugGame  \
	UnrealFileServer-Linux-Shipping  \
	UnrealFileServer-Linux-Test  \
	UnrealFileServer \
	UnrealFrontend-Linux-Debug  \
	UnrealFrontend-Linux-DebugGame  \
	UnrealFrontend-Linux-Shipping  \
	UnrealFrontend-Linux-Test  \
	UnrealFrontend \
	UnrealHeaderTool-Linux-Debug  \
	UnrealHeaderTool-Linux-DebugGame  \
	UnrealHeaderTool-Linux-Shipping  \
	UnrealHeaderTool-Linux-Test  \
	UnrealHeaderTool \
	UnrealInsights-Linux-Debug  \
	UnrealInsights-Linux-DebugGame  \
	UnrealInsights-Linux-Shipping  \
	UnrealInsights-Linux-Test  \
	UnrealInsights \
	UnrealLightmass-Linux-Debug  \
	UnrealLightmass-Linux-DebugGame  \
	UnrealLightmass-Linux-Shipping  \
	UnrealLightmass-Linux-Test  \
	UnrealLightmass \
	UnrealMultiUserServer-Linux-Debug  \
	UnrealMultiUserServer-Linux-DebugGame  \
	UnrealMultiUserServer-Linux-Shipping  \
	UnrealMultiUserServer-Linux-Test  \
	UnrealMultiUserServer \
	UnrealObjectPtrTool-Linux-Debug  \
	UnrealObjectPtrTool-Linux-DebugGame  \
	UnrealObjectPtrTool-Linux-Shipping  \
	UnrealObjectPtrTool-Linux-Test  \
	UnrealObjectPtrTool \
	UnrealPak-Linux-Debug  \
	UnrealPak-Linux-DebugGame  \
	UnrealPak-Linux-Shipping  \
	UnrealPak-Linux-Test  \
	UnrealPak \
	UnrealRecoverySvc-Linux-Debug  \
	UnrealRecoverySvc-Linux-DebugGame  \
	UnrealRecoverySvc-Linux-Shipping  \
	UnrealRecoverySvc-Linux-Test  \
	UnrealRecoverySvc \
	UnrealVersionSelector-Linux-Debug  \
	UnrealVersionSelector-Linux-DebugGame  \
	UnrealVersionSelector-Linux-Shipping  \
	UnrealVersionSelector-Linux-Test  \
	UnrealVersionSelector \
	TextureShareSDK_D3D11-Linux-Debug  \
	TextureShareSDK_D3D11-Linux-DebugGame  \
	TextureShareSDK_D3D11-Linux-Shipping  \
	TextureShareSDK_D3D11-Linux-Test  \
	TextureShareSDK_D3D11 \
	TextureShareSDK_D3D12-Linux-Debug  \
	TextureShareSDK_D3D12-Linux-DebugGame  \
	TextureShareSDK_D3D12-Linux-Shipping  \
	TextureShareSDK_D3D12-Linux-Test  \
	TextureShareSDK_D3D12 \
	BootstrapPackagedGame-Linux-Debug  \
	BootstrapPackagedGame-Linux-DebugGame  \
	BootstrapPackagedGame-Linux-Shipping  \
	BootstrapPackagedGame-Linux-Test  \
	BootstrapPackagedGame \
	UnrealClient-Linux-Debug  \
	UnrealClient-Linux-DebugGame  \
	UnrealClient-Linux-Shipping  \
	UnrealClient-Linux-Test  \
	UnrealClient \
	UnrealEditor-Linux-Debug  \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Shipping  \
	UnrealEditor-Linux-Test  \
	UnrealEditor \
	UnrealGame-Linux-Debug  \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Shipping  \
	UnrealGame-Linux-Test  \
	UnrealGame \
	UnrealServer-Linux-Debug  \
	UnrealServer-Linux-DebugGame  \
	UnrealServer-Linux-Shipping  \
	UnrealServer-Linux-Test  \
	UnrealServer \
	Building_Escape_3-Linux-Debug  \
	Building_Escape_3-Linux-DebugGame  \
	Building_Escape_3-Linux-Shipping  \
	Building_Escape_3-Linux-Test  \
	Building_Escape_3 \
	Building_Escape_3Editor-Linux-Debug  \
	Building_Escape_3Editor-Linux-DebugGame  \
	Building_Escape_3Editor-Linux-Shipping  \
	Building_Escape_3Editor-Linux-Test  \
	Building_Escape_3Editor\
	configure

BUILD = bash "$(UNREALROOTPATH)/Engine/Build/BatchFiles/Linux/Build.sh"
PROJECTBUILD = bash "$(UNREALROOTPATH)/Engine/Build/BatchFiles/Linux/RunMono.sh" "$(UNREALROOTPATH)/Engine/Binaries/DotNET/UnrealBuildTool.exe"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend UnrealEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug UnrealEditor-Linux-Debug


BenchmarkTool-Linux-Debug:
	 $(BUILD) BenchmarkTool Linux Debug  $(ARGS)

BenchmarkTool-Linux-DebugGame:
	 $(BUILD) BenchmarkTool Linux DebugGame  $(ARGS)

BenchmarkTool-Linux-Shipping:
	 $(BUILD) BenchmarkTool Linux Shipping  $(ARGS)

BenchmarkTool-Linux-Test:
	 $(BUILD) BenchmarkTool Linux Test  $(ARGS)

BenchmarkTool:
	 $(BUILD) BenchmarkTool Linux Development  $(ARGS)

BlankProgram-Linux-Debug:
	 $(BUILD) BlankProgram Linux Debug  $(ARGS)

BlankProgram-Linux-DebugGame:
	 $(BUILD) BlankProgram Linux DebugGame  $(ARGS)

BlankProgram-Linux-Shipping:
	 $(BUILD) BlankProgram Linux Shipping  $(ARGS)

BlankProgram-Linux-Test:
	 $(BUILD) BlankProgram Linux Test  $(ARGS)

BlankProgram:
	 $(BUILD) BlankProgram Linux Development  $(ARGS)

BuildPatchTool-Linux-Debug:
	 $(BUILD) BuildPatchTool Linux Debug  $(ARGS)

BuildPatchTool-Linux-DebugGame:
	 $(BUILD) BuildPatchTool Linux DebugGame  $(ARGS)

BuildPatchTool-Linux-Shipping:
	 $(BUILD) BuildPatchTool Linux Shipping  $(ARGS)

BuildPatchTool-Linux-Test:
	 $(BUILD) BuildPatchTool Linux Test  $(ARGS)

BuildPatchTool:
	 $(BUILD) BuildPatchTool Linux Development  $(ARGS)

ChaosVisualDebugger-Linux-Debug:
	 $(BUILD) ChaosVisualDebugger Linux Debug  $(ARGS)

ChaosVisualDebugger-Linux-DebugGame:
	 $(BUILD) ChaosVisualDebugger Linux DebugGame  $(ARGS)

ChaosVisualDebugger-Linux-Shipping:
	 $(BUILD) ChaosVisualDebugger Linux Shipping  $(ARGS)

ChaosVisualDebugger-Linux-Test:
	 $(BUILD) ChaosVisualDebugger Linux Test  $(ARGS)

ChaosVisualDebugger:
	 $(BUILD) ChaosVisualDebugger Linux Development  $(ARGS)

CrashReportClient-Linux-Debug:
	 $(BUILD) CrashReportClient Linux Debug  $(ARGS)

CrashReportClient-Linux-DebugGame:
	 $(BUILD) CrashReportClient Linux DebugGame  $(ARGS)

CrashReportClient-Linux-Shipping:
	 $(BUILD) CrashReportClient Linux Shipping  $(ARGS)

CrashReportClient-Linux-Test:
	 $(BUILD) CrashReportClient Linux Test  $(ARGS)

CrashReportClient:
	 $(BUILD) CrashReportClient Linux Development  $(ARGS)

CrashReportClientEditor-Linux-Debug:
	 $(BUILD) CrashReportClientEditor Linux Debug  $(ARGS)

CrashReportClientEditor-Linux-DebugGame:
	 $(BUILD) CrashReportClientEditor Linux DebugGame  $(ARGS)

CrashReportClientEditor-Linux-Shipping:
	 $(BUILD) CrashReportClientEditor Linux Shipping  $(ARGS)

CrashReportClientEditor-Linux-Test:
	 $(BUILD) CrashReportClientEditor Linux Test  $(ARGS)

CrashReportClientEditor:
	 $(BUILD) CrashReportClientEditor Linux Development  $(ARGS)

DatasmithCADWorker-Linux-Debug:
	 $(BUILD) DatasmithCADWorker Linux Debug  $(ARGS)

DatasmithCADWorker-Linux-DebugGame:
	 $(BUILD) DatasmithCADWorker Linux DebugGame  $(ARGS)

DatasmithCADWorker-Linux-Shipping:
	 $(BUILD) DatasmithCADWorker Linux Shipping  $(ARGS)

DatasmithCADWorker-Linux-Test:
	 $(BUILD) DatasmithCADWorker Linux Test  $(ARGS)

DatasmithCADWorker:
	 $(BUILD) DatasmithCADWorker Linux Development  $(ARGS)

DatasmithFacadeCSharp-Linux-Debug:
	 $(BUILD) DatasmithFacadeCSharp Linux Debug  $(ARGS)

DatasmithFacadeCSharp-Linux-DebugGame:
	 $(BUILD) DatasmithFacadeCSharp Linux DebugGame  $(ARGS)

DatasmithFacadeCSharp-Linux-Shipping:
	 $(BUILD) DatasmithFacadeCSharp Linux Shipping  $(ARGS)

DatasmithFacadeCSharp-Linux-Test:
	 $(BUILD) DatasmithFacadeCSharp Linux Test  $(ARGS)

DatasmithFacadeCSharp:
	 $(BUILD) DatasmithFacadeCSharp Linux Development  $(ARGS)

DatasmithMax2016-Linux-Debug:
	 $(BUILD) DatasmithMax2016 Linux Debug  $(ARGS)

DatasmithMax2016-Linux-DebugGame:
	 $(BUILD) DatasmithMax2016 Linux DebugGame  $(ARGS)

DatasmithMax2016-Linux-Shipping:
	 $(BUILD) DatasmithMax2016 Linux Shipping  $(ARGS)

DatasmithMax2016-Linux-Test:
	 $(BUILD) DatasmithMax2016 Linux Test  $(ARGS)

DatasmithMax2016:
	 $(BUILD) DatasmithMax2016 Linux Development  $(ARGS)

DatasmithMax2017-Linux-Debug:
	 $(BUILD) DatasmithMax2017 Linux Debug  $(ARGS)

DatasmithMax2017-Linux-DebugGame:
	 $(BUILD) DatasmithMax2017 Linux DebugGame  $(ARGS)

DatasmithMax2017-Linux-Shipping:
	 $(BUILD) DatasmithMax2017 Linux Shipping  $(ARGS)

DatasmithMax2017-Linux-Test:
	 $(BUILD) DatasmithMax2017 Linux Test  $(ARGS)

DatasmithMax2017:
	 $(BUILD) DatasmithMax2017 Linux Development  $(ARGS)

DatasmithMax2018-Linux-Debug:
	 $(BUILD) DatasmithMax2018 Linux Debug  $(ARGS)

DatasmithMax2018-Linux-DebugGame:
	 $(BUILD) DatasmithMax2018 Linux DebugGame  $(ARGS)

DatasmithMax2018-Linux-Shipping:
	 $(BUILD) DatasmithMax2018 Linux Shipping  $(ARGS)

DatasmithMax2018-Linux-Test:
	 $(BUILD) DatasmithMax2018 Linux Test  $(ARGS)

DatasmithMax2018:
	 $(BUILD) DatasmithMax2018 Linux Development  $(ARGS)

DatasmithMax2019-Linux-Debug:
	 $(BUILD) DatasmithMax2019 Linux Debug  $(ARGS)

DatasmithMax2019-Linux-DebugGame:
	 $(BUILD) DatasmithMax2019 Linux DebugGame  $(ARGS)

DatasmithMax2019-Linux-Shipping:
	 $(BUILD) DatasmithMax2019 Linux Shipping  $(ARGS)

DatasmithMax2019-Linux-Test:
	 $(BUILD) DatasmithMax2019 Linux Test  $(ARGS)

DatasmithMax2019:
	 $(BUILD) DatasmithMax2019 Linux Development  $(ARGS)

DatasmithMax2020-Linux-Debug:
	 $(BUILD) DatasmithMax2020 Linux Debug  $(ARGS)

DatasmithMax2020-Linux-DebugGame:
	 $(BUILD) DatasmithMax2020 Linux DebugGame  $(ARGS)

DatasmithMax2020-Linux-Shipping:
	 $(BUILD) DatasmithMax2020 Linux Shipping  $(ARGS)

DatasmithMax2020-Linux-Test:
	 $(BUILD) DatasmithMax2020 Linux Test  $(ARGS)

DatasmithMax2020:
	 $(BUILD) DatasmithMax2020 Linux Development  $(ARGS)

DatasmithMax2021-Linux-Debug:
	 $(BUILD) DatasmithMax2021 Linux Debug  $(ARGS)

DatasmithMax2021-Linux-DebugGame:
	 $(BUILD) DatasmithMax2021 Linux DebugGame  $(ARGS)

DatasmithMax2021-Linux-Shipping:
	 $(BUILD) DatasmithMax2021 Linux Shipping  $(ARGS)

DatasmithMax2021-Linux-Test:
	 $(BUILD) DatasmithMax2021 Linux Test  $(ARGS)

DatasmithMax2021:
	 $(BUILD) DatasmithMax2021 Linux Development  $(ARGS)

DatasmithNavisworks2019-Linux-Debug:
	 $(BUILD) DatasmithNavisworks2019 Linux Debug  $(ARGS)

DatasmithNavisworks2019-Linux-DebugGame:
	 $(BUILD) DatasmithNavisworks2019 Linux DebugGame  $(ARGS)

DatasmithNavisworks2019-Linux-Shipping:
	 $(BUILD) DatasmithNavisworks2019 Linux Shipping  $(ARGS)

DatasmithNavisworks2019-Linux-Test:
	 $(BUILD) DatasmithNavisworks2019 Linux Test  $(ARGS)

DatasmithNavisworks2019:
	 $(BUILD) DatasmithNavisworks2019 Linux Development  $(ARGS)

DatasmithNavisworks2020-Linux-Debug:
	 $(BUILD) DatasmithNavisworks2020 Linux Debug  $(ARGS)

DatasmithNavisworks2020-Linux-DebugGame:
	 $(BUILD) DatasmithNavisworks2020 Linux DebugGame  $(ARGS)

DatasmithNavisworks2020-Linux-Shipping:
	 $(BUILD) DatasmithNavisworks2020 Linux Shipping  $(ARGS)

DatasmithNavisworks2020-Linux-Test:
	 $(BUILD) DatasmithNavisworks2020 Linux Test  $(ARGS)

DatasmithNavisworks2020:
	 $(BUILD) DatasmithNavisworks2020 Linux Development  $(ARGS)

DatasmithRevit2018-Linux-Debug:
	 $(BUILD) DatasmithRevit2018 Linux Debug  $(ARGS)

DatasmithRevit2018-Linux-DebugGame:
	 $(BUILD) DatasmithRevit2018 Linux DebugGame  $(ARGS)

DatasmithRevit2018-Linux-Shipping:
	 $(BUILD) DatasmithRevit2018 Linux Shipping  $(ARGS)

DatasmithRevit2018-Linux-Test:
	 $(BUILD) DatasmithRevit2018 Linux Test  $(ARGS)

DatasmithRevit2018:
	 $(BUILD) DatasmithRevit2018 Linux Development  $(ARGS)

DatasmithRevit2019-Linux-Debug:
	 $(BUILD) DatasmithRevit2019 Linux Debug  $(ARGS)

DatasmithRevit2019-Linux-DebugGame:
	 $(BUILD) DatasmithRevit2019 Linux DebugGame  $(ARGS)

DatasmithRevit2019-Linux-Shipping:
	 $(BUILD) DatasmithRevit2019 Linux Shipping  $(ARGS)

DatasmithRevit2019-Linux-Test:
	 $(BUILD) DatasmithRevit2019 Linux Test  $(ARGS)

DatasmithRevit2019:
	 $(BUILD) DatasmithRevit2019 Linux Development  $(ARGS)

DatasmithRevit2020-Linux-Debug:
	 $(BUILD) DatasmithRevit2020 Linux Debug  $(ARGS)

DatasmithRevit2020-Linux-DebugGame:
	 $(BUILD) DatasmithRevit2020 Linux DebugGame  $(ARGS)

DatasmithRevit2020-Linux-Shipping:
	 $(BUILD) DatasmithRevit2020 Linux Shipping  $(ARGS)

DatasmithRevit2020-Linux-Test:
	 $(BUILD) DatasmithRevit2020 Linux Test  $(ARGS)

DatasmithRevit2020:
	 $(BUILD) DatasmithRevit2020 Linux Development  $(ARGS)

DatasmithRevit2021-Linux-Debug:
	 $(BUILD) DatasmithRevit2021 Linux Debug  $(ARGS)

DatasmithRevit2021-Linux-DebugGame:
	 $(BUILD) DatasmithRevit2021 Linux DebugGame  $(ARGS)

DatasmithRevit2021-Linux-Shipping:
	 $(BUILD) DatasmithRevit2021 Linux Shipping  $(ARGS)

DatasmithRevit2021-Linux-Test:
	 $(BUILD) DatasmithRevit2021 Linux Test  $(ARGS)

DatasmithRevit2021:
	 $(BUILD) DatasmithRevit2021 Linux Development  $(ARGS)

DatasmithRhino6-Linux-Debug:
	 $(BUILD) DatasmithRhino6 Linux Debug  $(ARGS)

DatasmithRhino6-Linux-DebugGame:
	 $(BUILD) DatasmithRhino6 Linux DebugGame  $(ARGS)

DatasmithRhino6-Linux-Shipping:
	 $(BUILD) DatasmithRhino6 Linux Shipping  $(ARGS)

DatasmithRhino6-Linux-Test:
	 $(BUILD) DatasmithRhino6 Linux Test  $(ARGS)

DatasmithRhino6:
	 $(BUILD) DatasmithRhino6 Linux Development  $(ARGS)

DatasmithRhino7-Linux-Debug:
	 $(BUILD) DatasmithRhino7 Linux Debug  $(ARGS)

DatasmithRhino7-Linux-DebugGame:
	 $(BUILD) DatasmithRhino7 Linux DebugGame  $(ARGS)

DatasmithRhino7-Linux-Shipping:
	 $(BUILD) DatasmithRhino7 Linux Shipping  $(ARGS)

DatasmithRhino7-Linux-Test:
	 $(BUILD) DatasmithRhino7 Linux Test  $(ARGS)

DatasmithRhino7:
	 $(BUILD) DatasmithRhino7 Linux Development  $(ARGS)

DatasmithSDK-Linux-Debug:
	 $(BUILD) DatasmithSDK Linux Debug  $(ARGS)

DatasmithSDK-Linux-DebugGame:
	 $(BUILD) DatasmithSDK Linux DebugGame  $(ARGS)

DatasmithSDK-Linux-Shipping:
	 $(BUILD) DatasmithSDK Linux Shipping  $(ARGS)

DatasmithSDK-Linux-Test:
	 $(BUILD) DatasmithSDK Linux Test  $(ARGS)

DatasmithSDK:
	 $(BUILD) DatasmithSDK Linux Development  $(ARGS)

DatasmithSketchUp2017-Linux-Debug:
	 $(BUILD) DatasmithSketchUp2017 Linux Debug  $(ARGS)

DatasmithSketchUp2017-Linux-DebugGame:
	 $(BUILD) DatasmithSketchUp2017 Linux DebugGame  $(ARGS)

DatasmithSketchUp2017-Linux-Shipping:
	 $(BUILD) DatasmithSketchUp2017 Linux Shipping  $(ARGS)

DatasmithSketchUp2017-Linux-Test:
	 $(BUILD) DatasmithSketchUp2017 Linux Test  $(ARGS)

DatasmithSketchUp2017:
	 $(BUILD) DatasmithSketchUp2017 Linux Development  $(ARGS)

DatasmithSketchUp2018-Linux-Debug:
	 $(BUILD) DatasmithSketchUp2018 Linux Debug  $(ARGS)

DatasmithSketchUp2018-Linux-DebugGame:
	 $(BUILD) DatasmithSketchUp2018 Linux DebugGame  $(ARGS)

DatasmithSketchUp2018-Linux-Shipping:
	 $(BUILD) DatasmithSketchUp2018 Linux Shipping  $(ARGS)

DatasmithSketchUp2018-Linux-Test:
	 $(BUILD) DatasmithSketchUp2018 Linux Test  $(ARGS)

DatasmithSketchUp2018:
	 $(BUILD) DatasmithSketchUp2018 Linux Development  $(ARGS)

DatasmithSketchUp2019-Linux-Debug:
	 $(BUILD) DatasmithSketchUp2019 Linux Debug  $(ARGS)

DatasmithSketchUp2019-Linux-DebugGame:
	 $(BUILD) DatasmithSketchUp2019 Linux DebugGame  $(ARGS)

DatasmithSketchUp2019-Linux-Shipping:
	 $(BUILD) DatasmithSketchUp2019 Linux Shipping  $(ARGS)

DatasmithSketchUp2019-Linux-Test:
	 $(BUILD) DatasmithSketchUp2019 Linux Test  $(ARGS)

DatasmithSketchUp2019:
	 $(BUILD) DatasmithSketchUp2019 Linux Development  $(ARGS)

DatasmithSketchUp2020-Linux-Debug:
	 $(BUILD) DatasmithSketchUp2020 Linux Debug  $(ARGS)

DatasmithSketchUp2020-Linux-DebugGame:
	 $(BUILD) DatasmithSketchUp2020 Linux DebugGame  $(ARGS)

DatasmithSketchUp2020-Linux-Shipping:
	 $(BUILD) DatasmithSketchUp2020 Linux Shipping  $(ARGS)

DatasmithSketchUp2020-Linux-Test:
	 $(BUILD) DatasmithSketchUp2020 Linux Test  $(ARGS)

DatasmithSketchUp2020:
	 $(BUILD) DatasmithSketchUp2020 Linux Development  $(ARGS)

EpicWebHelper-Linux-Debug:
	 $(BUILD) EpicWebHelper Linux Debug  $(ARGS)

EpicWebHelper-Linux-DebugGame:
	 $(BUILD) EpicWebHelper Linux DebugGame  $(ARGS)

EpicWebHelper-Linux-Shipping:
	 $(BUILD) EpicWebHelper Linux Shipping  $(ARGS)

EpicWebHelper-Linux-Test:
	 $(BUILD) EpicWebHelper Linux Test  $(ARGS)

EpicWebHelper:
	 $(BUILD) EpicWebHelper Linux Development  $(ARGS)

HeadlessChaos-Linux-Debug:
	 $(BUILD) HeadlessChaos Linux Debug  $(ARGS)

HeadlessChaos-Linux-DebugGame:
	 $(BUILD) HeadlessChaos Linux DebugGame  $(ARGS)

HeadlessChaos-Linux-Shipping:
	 $(BUILD) HeadlessChaos Linux Shipping  $(ARGS)

HeadlessChaos-Linux-Test:
	 $(BUILD) HeadlessChaos Linux Test  $(ARGS)

HeadlessChaos:
	 $(BUILD) HeadlessChaos Linux Development  $(ARGS)

InterchangeWorker-Linux-Debug:
	 $(BUILD) InterchangeWorker Linux Debug  $(ARGS)

InterchangeWorker-Linux-DebugGame:
	 $(BUILD) InterchangeWorker Linux DebugGame  $(ARGS)

InterchangeWorker-Linux-Shipping:
	 $(BUILD) InterchangeWorker Linux Shipping  $(ARGS)

InterchangeWorker-Linux-Test:
	 $(BUILD) InterchangeWorker Linux Test  $(ARGS)

InterchangeWorker:
	 $(BUILD) InterchangeWorker Linux Development  $(ARGS)

LiveCodingConsole-Linux-Debug:
	 $(BUILD) LiveCodingConsole Linux Debug  $(ARGS)

LiveCodingConsole-Linux-DebugGame:
	 $(BUILD) LiveCodingConsole Linux DebugGame  $(ARGS)

LiveCodingConsole-Linux-Shipping:
	 $(BUILD) LiveCodingConsole Linux Shipping  $(ARGS)

LiveCodingConsole-Linux-Test:
	 $(BUILD) LiveCodingConsole Linux Test  $(ARGS)

LiveCodingConsole:
	 $(BUILD) LiveCodingConsole Linux Development  $(ARGS)

ShaderCompileWorker-Linux-Debug:
	 $(BUILD) ShaderCompileWorker Linux Debug  $(ARGS)

ShaderCompileWorker-Linux-DebugGame:
	 $(BUILD) ShaderCompileWorker Linux DebugGame  $(ARGS)

ShaderCompileWorker-Linux-Shipping:
	 $(BUILD) ShaderCompileWorker Linux Shipping  $(ARGS)

ShaderCompileWorker-Linux-Test:
	 $(BUILD) ShaderCompileWorker Linux Test  $(ARGS)

ShaderCompileWorker:
	 $(BUILD) ShaderCompileWorker Linux Development  $(ARGS)

SlateViewer-Linux-Debug:
	 $(BUILD) SlateViewer Linux Debug  $(ARGS)

SlateViewer-Linux-DebugGame:
	 $(BUILD) SlateViewer Linux DebugGame  $(ARGS)

SlateViewer-Linux-Shipping:
	 $(BUILD) SlateViewer Linux Shipping  $(ARGS)

SlateViewer-Linux-Test:
	 $(BUILD) SlateViewer Linux Test  $(ARGS)

SlateViewer:
	 $(BUILD) SlateViewer Linux Development  $(ARGS)

SwitchboardListener-Linux-Debug:
	 $(BUILD) SwitchboardListener Linux Debug  $(ARGS)

SwitchboardListener-Linux-DebugGame:
	 $(BUILD) SwitchboardListener Linux DebugGame  $(ARGS)

SwitchboardListener-Linux-Shipping:
	 $(BUILD) SwitchboardListener Linux Shipping  $(ARGS)

SwitchboardListener-Linux-Test:
	 $(BUILD) SwitchboardListener Linux Test  $(ARGS)

SwitchboardListener:
	 $(BUILD) SwitchboardListener Linux Development  $(ARGS)

TestPAL-Linux-Debug:
	 $(BUILD) TestPAL Linux Debug  $(ARGS)

TestPAL-Linux-DebugGame:
	 $(BUILD) TestPAL Linux DebugGame  $(ARGS)

TestPAL-Linux-Shipping:
	 $(BUILD) TestPAL Linux Shipping  $(ARGS)

TestPAL-Linux-Test:
	 $(BUILD) TestPAL Linux Test  $(ARGS)

TestPAL:
	 $(BUILD) TestPAL Linux Development  $(ARGS)

TextureShareSDK-Linux-Debug:
	 $(BUILD) TextureShareSDK Linux Debug  $(ARGS)

TextureShareSDK-Linux-DebugGame:
	 $(BUILD) TextureShareSDK Linux DebugGame  $(ARGS)

TextureShareSDK-Linux-Shipping:
	 $(BUILD) TextureShareSDK Linux Shipping  $(ARGS)

TextureShareSDK-Linux-Test:
	 $(BUILD) TextureShareSDK Linux Test  $(ARGS)

TextureShareSDK:
	 $(BUILD) TextureShareSDK Linux Development  $(ARGS)

UnrealFileServer-Linux-Debug:
	 $(BUILD) UnrealFileServer Linux Debug  $(ARGS)

UnrealFileServer-Linux-DebugGame:
	 $(BUILD) UnrealFileServer Linux DebugGame  $(ARGS)

UnrealFileServer-Linux-Shipping:
	 $(BUILD) UnrealFileServer Linux Shipping  $(ARGS)

UnrealFileServer-Linux-Test:
	 $(BUILD) UnrealFileServer Linux Test  $(ARGS)

UnrealFileServer:
	 $(BUILD) UnrealFileServer Linux Development  $(ARGS)

UnrealFrontend-Linux-Debug:
	 $(BUILD) UnrealFrontend Linux Debug  $(ARGS)

UnrealFrontend-Linux-DebugGame:
	 $(BUILD) UnrealFrontend Linux DebugGame  $(ARGS)

UnrealFrontend-Linux-Shipping:
	 $(BUILD) UnrealFrontend Linux Shipping  $(ARGS)

UnrealFrontend-Linux-Test:
	 $(BUILD) UnrealFrontend Linux Test  $(ARGS)

UnrealFrontend:
	 $(BUILD) UnrealFrontend Linux Development  $(ARGS)

UnrealHeaderTool-Linux-Debug:
	 $(BUILD) UnrealHeaderTool Linux Debug  $(ARGS)

UnrealHeaderTool-Linux-DebugGame:
	 $(BUILD) UnrealHeaderTool Linux DebugGame  $(ARGS)

UnrealHeaderTool-Linux-Shipping:
	 $(BUILD) UnrealHeaderTool Linux Shipping  $(ARGS)

UnrealHeaderTool-Linux-Test:
	 $(BUILD) UnrealHeaderTool Linux Test  $(ARGS)

UnrealHeaderTool:
	 $(BUILD) UnrealHeaderTool Linux Development  $(ARGS)

UnrealInsights-Linux-Debug:
	 $(BUILD) UnrealInsights Linux Debug  $(ARGS)

UnrealInsights-Linux-DebugGame:
	 $(BUILD) UnrealInsights Linux DebugGame  $(ARGS)

UnrealInsights-Linux-Shipping:
	 $(BUILD) UnrealInsights Linux Shipping  $(ARGS)

UnrealInsights-Linux-Test:
	 $(BUILD) UnrealInsights Linux Test  $(ARGS)

UnrealInsights:
	 $(BUILD) UnrealInsights Linux Development  $(ARGS)

UnrealLightmass-Linux-Debug:
	 $(BUILD) UnrealLightmass Linux Debug  $(ARGS)

UnrealLightmass-Linux-DebugGame:
	 $(BUILD) UnrealLightmass Linux DebugGame  $(ARGS)

UnrealLightmass-Linux-Shipping:
	 $(BUILD) UnrealLightmass Linux Shipping  $(ARGS)

UnrealLightmass-Linux-Test:
	 $(BUILD) UnrealLightmass Linux Test  $(ARGS)

UnrealLightmass:
	 $(BUILD) UnrealLightmass Linux Development  $(ARGS)

UnrealMultiUserServer-Linux-Debug:
	 $(BUILD) UnrealMultiUserServer Linux Debug  $(ARGS)

UnrealMultiUserServer-Linux-DebugGame:
	 $(BUILD) UnrealMultiUserServer Linux DebugGame  $(ARGS)

UnrealMultiUserServer-Linux-Shipping:
	 $(BUILD) UnrealMultiUserServer Linux Shipping  $(ARGS)

UnrealMultiUserServer-Linux-Test:
	 $(BUILD) UnrealMultiUserServer Linux Test  $(ARGS)

UnrealMultiUserServer:
	 $(BUILD) UnrealMultiUserServer Linux Development  $(ARGS)

UnrealObjectPtrTool-Linux-Debug:
	 $(BUILD) UnrealObjectPtrTool Linux Debug  $(ARGS)

UnrealObjectPtrTool-Linux-DebugGame:
	 $(BUILD) UnrealObjectPtrTool Linux DebugGame  $(ARGS)

UnrealObjectPtrTool-Linux-Shipping:
	 $(BUILD) UnrealObjectPtrTool Linux Shipping  $(ARGS)

UnrealObjectPtrTool-Linux-Test:
	 $(BUILD) UnrealObjectPtrTool Linux Test  $(ARGS)

UnrealObjectPtrTool:
	 $(BUILD) UnrealObjectPtrTool Linux Development  $(ARGS)

UnrealPak-Linux-Debug:
	 $(BUILD) UnrealPak Linux Debug  $(ARGS)

UnrealPak-Linux-DebugGame:
	 $(BUILD) UnrealPak Linux DebugGame  $(ARGS)

UnrealPak-Linux-Shipping:
	 $(BUILD) UnrealPak Linux Shipping  $(ARGS)

UnrealPak-Linux-Test:
	 $(BUILD) UnrealPak Linux Test  $(ARGS)

UnrealPak:
	 $(BUILD) UnrealPak Linux Development  $(ARGS)

UnrealRecoverySvc-Linux-Debug:
	 $(BUILD) UnrealRecoverySvc Linux Debug  $(ARGS)

UnrealRecoverySvc-Linux-DebugGame:
	 $(BUILD) UnrealRecoverySvc Linux DebugGame  $(ARGS)

UnrealRecoverySvc-Linux-Shipping:
	 $(BUILD) UnrealRecoverySvc Linux Shipping  $(ARGS)

UnrealRecoverySvc-Linux-Test:
	 $(BUILD) UnrealRecoverySvc Linux Test  $(ARGS)

UnrealRecoverySvc:
	 $(BUILD) UnrealRecoverySvc Linux Development  $(ARGS)

UnrealVersionSelector-Linux-Debug:
	 $(BUILD) UnrealVersionSelector Linux Debug  $(ARGS)

UnrealVersionSelector-Linux-DebugGame:
	 $(BUILD) UnrealVersionSelector Linux DebugGame  $(ARGS)

UnrealVersionSelector-Linux-Shipping:
	 $(BUILD) UnrealVersionSelector Linux Shipping  $(ARGS)

UnrealVersionSelector-Linux-Test:
	 $(BUILD) UnrealVersionSelector Linux Test  $(ARGS)

UnrealVersionSelector:
	 $(BUILD) UnrealVersionSelector Linux Development  $(ARGS)

TextureShareSDK_D3D11-Linux-Debug:
	 $(BUILD) TextureShareSDK_D3D11 Linux Debug  $(ARGS)

TextureShareSDK_D3D11-Linux-DebugGame:
	 $(BUILD) TextureShareSDK_D3D11 Linux DebugGame  $(ARGS)

TextureShareSDK_D3D11-Linux-Shipping:
	 $(BUILD) TextureShareSDK_D3D11 Linux Shipping  $(ARGS)

TextureShareSDK_D3D11-Linux-Test:
	 $(BUILD) TextureShareSDK_D3D11 Linux Test  $(ARGS)

TextureShareSDK_D3D11:
	 $(BUILD) TextureShareSDK_D3D11 Linux Development  $(ARGS)

TextureShareSDK_D3D12-Linux-Debug:
	 $(BUILD) TextureShareSDK_D3D12 Linux Debug  $(ARGS)

TextureShareSDK_D3D12-Linux-DebugGame:
	 $(BUILD) TextureShareSDK_D3D12 Linux DebugGame  $(ARGS)

TextureShareSDK_D3D12-Linux-Shipping:
	 $(BUILD) TextureShareSDK_D3D12 Linux Shipping  $(ARGS)

TextureShareSDK_D3D12-Linux-Test:
	 $(BUILD) TextureShareSDK_D3D12 Linux Test  $(ARGS)

TextureShareSDK_D3D12:
	 $(BUILD) TextureShareSDK_D3D12 Linux Development  $(ARGS)

BootstrapPackagedGame-Linux-Debug:
	 $(BUILD) BootstrapPackagedGame Linux Debug  $(ARGS)

BootstrapPackagedGame-Linux-DebugGame:
	 $(BUILD) BootstrapPackagedGame Linux DebugGame  $(ARGS)

BootstrapPackagedGame-Linux-Shipping:
	 $(BUILD) BootstrapPackagedGame Linux Shipping  $(ARGS)

BootstrapPackagedGame-Linux-Test:
	 $(BUILD) BootstrapPackagedGame Linux Test  $(ARGS)

BootstrapPackagedGame:
	 $(BUILD) BootstrapPackagedGame Linux Development  $(ARGS)

UnrealClient-Linux-Debug:
	 $(BUILD) UnrealClient Linux Debug  $(ARGS)

UnrealClient-Linux-DebugGame:
	 $(BUILD) UnrealClient Linux DebugGame  $(ARGS)

UnrealClient-Linux-Shipping:
	 $(BUILD) UnrealClient Linux Shipping  $(ARGS)

UnrealClient-Linux-Test:
	 $(BUILD) UnrealClient Linux Test  $(ARGS)

UnrealClient:
	 $(BUILD) UnrealClient Linux Development  $(ARGS)

UnrealEditor-Linux-Debug:
	 $(BUILD) UnrealEditor Linux Debug  $(ARGS)

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  $(ARGS)

UnrealEditor-Linux-Shipping:
	 $(BUILD) UnrealEditor Linux Shipping  $(ARGS)

UnrealEditor-Linux-Test:
	 $(BUILD) UnrealEditor Linux Test  $(ARGS)

UnrealEditor:
	 $(BUILD) UnrealEditor Linux Development  $(ARGS)

UnrealGame-Linux-Debug:
	 $(BUILD) UnrealGame Linux Debug  $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  $(ARGS)

UnrealGame-Linux-Test:
	 $(BUILD) UnrealGame Linux Test  $(ARGS)

UnrealGame:
	 $(BUILD) UnrealGame Linux Development  $(ARGS)

UnrealServer-Linux-Debug:
	 $(BUILD) UnrealServer Linux Debug  $(ARGS)

UnrealServer-Linux-DebugGame:
	 $(BUILD) UnrealServer Linux DebugGame  $(ARGS)

UnrealServer-Linux-Shipping:
	 $(BUILD) UnrealServer Linux Shipping  $(ARGS)

UnrealServer-Linux-Test:
	 $(BUILD) UnrealServer Linux Test  $(ARGS)

UnrealServer:
	 $(BUILD) UnrealServer Linux Development  $(ARGS)

Building_Escape_3-Linux-Debug:
	 $(PROJECTBUILD) Building_Escape_3 Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

Building_Escape_3-Linux-DebugGame:
	 $(PROJECTBUILD) Building_Escape_3 Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

Building_Escape_3-Linux-Shipping:
	 $(PROJECTBUILD) Building_Escape_3 Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

Building_Escape_3-Linux-Test:
	 $(PROJECTBUILD) Building_Escape_3 Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

Building_Escape_3:
	 $(PROJECTBUILD) Building_Escape_3 Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

Building_Escape_3Editor-Linux-Debug:
	 $(PROJECTBUILD) Building_Escape_3Editor Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

Building_Escape_3Editor-Linux-DebugGame:
	 $(PROJECTBUILD) Building_Escape_3Editor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

Building_Escape_3Editor-Linux-Shipping:
	 $(PROJECTBUILD) Building_Escape_3Editor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

Building_Escape_3Editor-Linux-Test:
	 $(PROJECTBUILD) Building_Escape_3Editor Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

Building_Escape_3Editor:
	 $(PROJECTBUILD) Building_Escape_3Editor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

configure:
	xbuild /property:Configuration=Development /verbosity:quiet /nologo "$(UNREALROOTPATH)/Engine/Source/Programs/UnrealBuildTool/UnrealBuildTool.csproj"
	$(PROJECTBUILD) -projectfiles -project="\"$(GAMEPROJECTFILE)\"" -game -engine 

.PHONY: $(TARGETS)
